global:
  scrape_interval: 5s 

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: postgres
    static_configs:
      - targets: ['postgres-benchmark_prom_postgres_exporter_1:9187']
        labels:
          alias: postgres
